### PR TITLE
Allow borderRadius to be set to an Array

### PR DESCRIPTION
**Pull request by eelco**
This allows the `borderRadius` of a `Layer` to be set to an array, to have different radiuses for different corners.

TODO:
- [ ] Add tests

### CODE REVIEW

**Comment by jordandobson** [comment]
You can already do this by passing a string. I like where you are going
here though.

**Comment by eelco** [comment]
Good point, I noticed that it currently has a ‘compatibility fix’ in the code, I assume that’s for passing strings? Would it make sense to tighten the API up and remove this?

**Comment by eelco** [comment]
Post-future.

**Comment by jordandobson** [comment]
👍🏼

**Pull request closed without merging**
