### PR TITLE
[TextLayer] Fixed size, frame (constructor) and constraints.width (autoSize) if layer has no parent

### PR DESCRIPTION
**Pull request by marckrenn**
Proposed fixes for #495 and #493.

Compare test cases with [framer.debug.js](https://framer.cloud/ztgmU/) and with current [framer.js](https://framer.cloud/GsEHH/).

### CODE REVIEW

**Comment by nvh** [comment]
This looks ok to me, would it be possible for you to add some tests?

**Comment by marckrenn** [comment]
Sure, give me a day or two.

**Comment by marckrenn** [comment]
One test case requires the TextLayer's parent to be Screen and to check the resulting `width = Screen.width - padding.left - padding.right`.

Is there a hardcoded `Screen.width` or how am I supposed to test that, @nvh?

Thanks for taking the time!

**Comment by nvh** [comment]
Sorry for not getting back to you sooner, but in the tests the screen size is defined by the test runner and fixed to `{width:400, height:300}`

**Comment by marckrenn** [comment]
Totally forgot about about this! Sorry, @nvh !

**Comment by nvh** [comment]
No worries at all! The new TextLayer should fix it :)

**Pull request closed without merging**
