### PR TITLE
Ability of adding and removing multiple subLayers

### PR DESCRIPTION
**Pull request by fliptheweb**

### CODE REVIEW

**Comment by edwinvanrijkom** [comment]
Looks good! Thanks for contributing. What do you think @koenbok?

**Comment by ajimix** [comment]
Shouldn't it be a new method? addSublayers and removeSublayers? In the future addSublayer and removeSublayer could be deprecated.

**Comment by edwinvanrijkom** [comment]
I don't think it has to be a new method perse, for the proposed one is polymorph: it accepts both a single layer, as well as an Array of layers, so it isn't breaking the 'old' API.

**Comment by ajimix** [comment]
Yes I know but it makes more sense as it's clearer but anyway, it's a matter of taste :)

**Comment by edwinvanrijkom** [comment]
Yeah, true :-) The only rational argument that I can come up with is that it's clearest to name it after the most common use case, which probably is adding/removing a single Layer?

**Comment by koenbok** [comment]
Hmm all valid, but such a small change I'm ok with whatever. But we will need some tests at the very least.

**Pull request closed without merging**
